### PR TITLE
Removed Boost dependency and fixed folder name transfers. Closes #115.

### LINKED ISSUE #115: Change Boost dependency
MASTODON won't compile without Boost because there is a Boost header directly included in MastodonUtils.h.

### PR DESCRIPTION
**Pull request by cbolisetti**

### CODE REVIEW

File: include/utils/MastodonUtils.h [hunk 1]
```diff
@@ -18,7 +18,7 @@
 // MOOSE includes
 #include "GeneralVectorPostprocessor.h"
 // Other includes
-#include <boost/math/distributions.hpp>
+#include "BoostDistribution.h"
```
Comment (aeslaughter) [inline include/utils/MastodonUtils.h]: I think that this can just be removed. Also the `boost::math::quantile` and similar methods should be changed to be `T.quantile()`, etc.

File: unit/include/base/Mastodon-unitRevision.h [hunk 2]
```diff
@@ -3,7 +3,7 @@
 #ifndef MASTODONUNIT_REVISION_H
 #define MASTODONUNIT_REVISION_H
 
-#define MASTODONUNIT_REVISION "git commit 221d9cc on 2018-01-17"
```
Comment (aeslaughter) [inline unit/include/base/Mastodon-unitRevision.h]: Can you remove this file from git please.

**Comment by brianmoose** [comment]
FYI, I added a "Test no boost" to all Mastodon PRs. It is currently "Allowed to Fail" and will be changed to a hard fail once it passes.
Just letting you know since it is not obvious when it fails, and it is failing on this PR...

File: unit/include/base/Mastodon-unitRevision.h (hunk 2 above)
Comment (aeslaughter) [reply unit/include/base/Mastodon-unitRevision.h]: @cbolisetti Please remove this file, it should not be in the repository.

File: include/utils/MastodonUtils.h (hunk 1 above)
Comment (cbolisetti) [reply include/utils/MastodonUtils.h]: I kept BoostDistribution.h since I am using Boost distributions in the greaterProbability function template in MastodonUtils.h.
