### PR TITLE
Fixed MastodonModelAction to be compatible with 1D and 2D simulations

### LINKED ISSUE #162: Fix MastodonModelAction to include 2D simulations
Need to remove a bug that results in an error for 2D simulations. Also need to create a test for 2D.

### PR DESCRIPTION
**Pull request by cbolisetti**
Added 2D tests.

Closes #162.

### CODE REVIEW

File: src/actions/MastodonModelAction.C [hunk 1]
```diff
@@ -41,9 +41,13 @@ validParams<MastodonModelAction>()
                              "acceleration AuxVariables and AuxKernels, inertia kernels and the "
                              "DynamicTensorMechanicsAction based on the dimension of the mesh and "
                              "if static or dynamic analysis is being performed.");
+  params.addParam<std::vector<SubdomainName>>("block",
+                                              "A list of ids of the blocks (subdomains) "
+                                              "that these model parameters apply to.");
   params.addParam<bool>("dynamic_analysis", true, "false, if static analysis is to be performed.");
   params.addParam<Real>("beta", 0.25, "beta parameter for Newmark time integration.");
   params.addParam<Real>("gamma", 0.5, "gamma parameter for Newmark time integration.");
+  params.addParam<unsigned int>("dim", 3, "Dimension of the mesh.");
```
Comment (aeslaughter) [inline src/actions/MastodonModelAction.C]: You should make this a MooseEnum, then you won't need to do the error check below.

```cpp
MooseEnum dim("1 2 3", "3");
params.addParam<MooseEnum>("dim", dim, ...);
```

File: src/actions/MastodonModelAction.C [hunk 2]
```diff
@@ -58,8 +62,13 @@ MastodonModelAction::MastodonModelAction(const InputParameters & params)
     _disp_variables({"disp_x", "disp_y", "disp_z"}),
     _vel_auxvariables({"vel_x", "vel_y", "vel_z"}),
     _accel_auxvariables({"accel_x", "accel_y", "accel_z"}),
+    _dim(getParam<unsigned int>("dim")),
```
Comment (aeslaughter) [inline src/actions/MastodonModelAction.C]: This would get changed to `<MooseEnum>`, but the use of `_dim` remains the same.

File: src/actions/MastodonModelAction.C [hunk 3]
```diff
@@ -58,8 +62,13 @@ MastodonModelAction::MastodonModelAction(const InputParameters & params)
...
     _use_displaced_mesh(getParam<bool>("use_displaced_mesh"))
 {
+  if (_dim < 1 || _dim > 3)
```
Comment (aeslaughter) [inline src/actions/MastodonModelAction.C]: This can go away if you change to MooseEnum

File: src/actions/MastodonModelAction.C [hunk 4]
```diff
@@ -47,7 +47,8 @@ validParams<MastodonModelAction>()
   params.addParam<bool>("dynamic_analysis", true, "false, if static analysis is to be performed.");
   params.addParam<Real>("beta", 0.25, "beta parameter for Newmark time integration.");
   params.addParam<Real>("gamma", 0.5, "gamma parameter for Newmark time integration.");
-  params.addParam<unsigned int>("dim", 3, "Dimension of the mesh.");
+  MooseEnum dim("1 2 3", "3");
```
Comment (aeslaughter) [inline src/actions/MastodonModelAction.C]: If you do: "1=1 2=2 3=3" then you do not need to to _dim + 1.

Comment (aeslaughter) [reply src/actions/MastodonModelAction.C]: The left side is the enum string the right side is the enum integer value.

Comment (cbolisetti) [reply src/actions/MastodonModelAction.C]: Oh, I was wondering how to do that. Good to know!
